# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :build_app_for_uitests do
    cocoapods(
      podfile: "Podfile",
      #repo_update: true,
      use_bundle_exec: true
    )
    gym(
      scheme: "AppodealSwiftDemo",
      workspace: "AppodealDemo.xcworkspace",
      configuration: "Debug",
      export_method: "development",
      # export_options: {},
      output_directory: "appium"
    )
  end
end
